# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

pod 'KakaoSDKCommon' # 필수 요소를 담은 공통 모듈
pod 'KakaoSDKAuth' # 카카오 로그인
pod 'KakaoSDKUser' # 사용자 관리
pod 'GoogleSignIn'
pod 'FBSDKLoginKit'
target 'SNSLoginExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SNSLoginExample

end
